CREATE TABLE PESSOA
(
	CODIGO BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
	ATIVO TINYINT(1) NOT NULL DEFAULT 0,
	LOGRADOURO VARCHAR(30) NOT NULL,
	NUMERO VARCHAR(6) NOT NULL DEFAULT 'S/N',
	COMPLEMENTO VARCHAR(80),
	BAIRRO VARCHAR(30) NOT NULL,
	CEP VARCHAR(9) NOT NULL,
	CIDADE VARCHAR(20) NOT NULL,
	ESTADO VARCHAR(2) NOT NULL
	
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO PESSOA (NOME, ATIVO, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, ESTADO)
			VALUES('Thiago', 1, 'Rua Sorocaba', '20A', '', 'Marcilio de Noronha', '29135372', 'Viana', 'ES');
