CREATE TABLE LANCAMENTO
(
	CODIGO BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO VARCHAR(50) NOT NULL,
	DATA_PAGAMENTO DATE NOT NULL,
	DATA_LANCAMENTO DATE NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL,
	OBSERVACAO VARCHAR(100),
	TIPO VARCHAR(20) NOT NULL,
	CODIGO_CATEGORIA BIGINT(20) NOT NULL,
	CODIGO_PESSOA BIGINT(20) NOT NULL,
	FOREIGN KEY (CODIGO_CATEGORIA) REFERENCES CATEGORIA(CODIGO),
	FOREIGN KEY (CODIGO_PESSOA) REFERENCES PESSOA(CODIGO)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO LANCAMENTO (DESCRICAO, DATA_PAGAMENTO, DATA_LANCAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA)
VALUES('Salario Mensal', '2017-08-28', '2017-09-01', 9500.00, '', 'RECEITA', 1,1);