CREATE TABLE USUARIO
(
	CODIGO BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	SENHA VARCHAR(150) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE PERMISSAO
(
	CODIGO BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO VARCHAR(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE USUARIO_PERMISSAO
(
	CODIGO_USUARIO BIGINT(20) NOT NULL,
	CODIGO_PERMISSAO BIGINT(20) NOT NULL,
    PRIMARY KEY(CODIGO_USUARIO, CODIGO_PERMISSAO),
	FOREIGN KEY (CODIGO_USUARIO) REFERENCES USUARIO(CODIGO),
	FOREIGN KEY (CODIGO_PERMISSAO) REFERENCES PERMISSAO(CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO USUARIO (CODIGO, NOME, EMAIL, SENHA) VALUES(1, 'Administrador', 'thiago.zeyu@gmail.com', '$2a$10$OHFcBbaAjdFZaGWrdG6EEORPt6Kl46hVi4mrdx7.y4YZi0VrpbbJu');

insert into permissao (CODIGO, descricao) values(1, 'ROLE_CADASTRAR_CATEGORIA');
insert into permissao (CODIGO, descricao) values(2, 'ROLE_PESQUISAR_CATEGORIA');
insert into permissao (CODIGO, descricao) values(3, 'ROLE_CADASTRAR_PESSOA');
insert into permissao (CODIGO, descricao) values(4, 'ROLE_PESQUISAR_PESSOA');
insert into permissao (CODIGO, descricao) values(5, 'ROLE_CADASTRAR_LANCAMENTO');
insert into permissao (CODIGO, descricao) values(6, 'ROLE_PESQUISAR_LANCAMENTO');

INSERT INTO USUARIO_PERMISSAO (CODIGO_USUARIO, CODIGO_PERMISSAO) VALUES (1,1);
INSERT INTO USUARIO_PERMISSAO (CODIGO_USUARIO, CODIGO_PERMISSAO) VALUES (1,2);
INSERT INTO USUARIO_PERMISSAO (CODIGO_USUARIO, CODIGO_PERMISSAO) VALUES (1,3);
INSERT INTO USUARIO_PERMISSAO (CODIGO_USUARIO, CODIGO_PERMISSAO) VALUES (1,4);